protected/models/Merchants.php
<?php

/**
 * This is the model class for table "merchants".
 *
 * The followings are the available columns in table 'merchants':
 * @property integer $merchant_id
 * @property integer $address_id
 * @property integer $company_id
 * @property integer $wh_id
 * @property integer $managed
 * @property integer $payment_terms
 */
class Merchants extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'merchants';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('merchant_id, address_id, company_id, wh_id, managed, payment_terms', 'required'),
			array('merchant_id, address_id, company_id, wh_id, managed, payment_terms', 'numerical', 'integerOnly'=>true),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('merchant_id, address_id, company_id, wh_id, managed, payment_terms', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
                    'address' => array(self::BELONGS_TO, 'Address', 'address_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'merchant_id' => 'Merchant',
			'address_id' => 'Address',
			'company_id' => 'Company',
			'wh_id' => 'Wh',
			'managed' => 'Managed',
			'payment_terms' => 'Payment Terms',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('merchant_id',$this->merchant_id);
		$criteria->compare('address_id',$this->address_id);
		$criteria->compare('company_id',$this->company_id);
		$criteria->compare('wh_id',$this->wh_id);
		$criteria->compare('managed',$this->managed);
		$criteria->compare('payment_terms',$this->payment_terms);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Merchants the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
        
        public function getMerchant($merchant_id){
            return self::model()->findByPk($merchant_id);
        }
}

protected/controllers/MerchantController.php
<?php

class MerchantController extends Controller
{
	public function actionIndex()
	{
		$this->render('index');
	}

	/**
	 * @return array action filters
	 */
	public function filters() {
            return array(
                'accessControl', // perform access control for CRUD operations
            );
        }

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(			
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('neworders','change','insertpurchase','confirmupdate','confirmedorders','markshiporders','export','cancelorders','test'),
				'roles'=>array('merchant','amazon'),
			),
                        array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('apipurchase','changepurchase'),
				'roles'=>array('amazon'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
        
        public function actionNeworders(){
            
            $date_range = $status_id = $filter_by = $filter_value = null;
            $model = new OrderProducts('neworder');
            $model->unsetAttributes();
            $model->status_id = ST_NEW;
            $merchant_id = Yii::app()->user->getId();
            
            if(isset($_GET['OrderProducts'])){               
                $date_range = $_GET['OrderProducts']['date_range'];
                
            }
            $this->render('new_orders',array(
                    'model'=>$model,
                    'status_id' => ST_NEW,
                    'merchant_id' => $merchant_id,
                    'date_range' => $date_range
            ));
        }
        
        /* 
         * Perform the status  change 
         * @param int $id op id 
         * @param int $status_id op_id
         */
        public function actionChange($id=null,$status_id=null){  
            
            $order_product = OrderProducts::model()->findByPk($id);
            if(!empty($order_product) && $order_product->status_id == 1){
                $order_product->status_id = (int)$status_id;
                if($order_product->save()){
                    if($order_product->status_id == 4){                        
                        $repsonse = OpMerchants::model()->resetMerchant($order_product->op_id);

                        $case_data = array();
                        $case_data['order_id'] = $order_product->order_id;
                        $case_data['cust_name'] = $order_product->order->address->first_name.' '.$order_product->order->address->last_name;
                        $case_data['cust_phone'] = $order_product->order->address->mobile;
                        $case_data['cust_email'] = $order_product->order->address->email;
                        $case_data['group_id'] = 111;  //purchase team
                        $case_data['owner'] = Yii::app()->user->getId();

                        $case_data['status'] = CASE_CLOSED;

                        //for case comment 

                        $case_data['user_id'] = Yii::app()->user->getId();
                        $case_data['type'] = 'cancellation'; //outbound interaction_type
                        $case_data['interaction_type'] = 4;                        
                        $case_data['comment'] = sprintf('Order Cancelled by Merchant %s(%d)',Yii::app()->user->getState('logged_user')->username,Yii::app()->user->getId());
                        $case_data['customer_rating'] = 0;
                        $res = Cases::model()->creatCase($case_data);
                        echo CJSON::encode($repsonse);
                    } 
                }
                
            }
            
            Yii::app()->end();
        }
        
        
        public function actionInsertPurchase($file_name=null){
            
                $tmp_file_path = realpath($this->upload_path_tmp).DIRECTORY_SEPARATOR.$file_name;                
                
                $file_info = new SplFileInfo($tmp_file_path);
                $file_extension = $file_info->getExtension();

                $work_sheet = Yii::app()->excel->reader($tmp_file_path,$file_extension);
                $data = Yii::app()->excel->getRawData($work_sheet);                
                
                $merchant_id = Yii::app()->user->getId();
                $merchant = Merchants::model()->getMerchant($merchant_id);
                
                $response = array();
                foreach($data as $_data){
                    $_data['wh_id'] = $merchant->wh_id;
                    $_data['merchant_id'] = $merchant_id;
                    if(isset($_data['condition']) && empty($_data['condition'])){
                        $_data['condition'] = CONDITION_NEW;
                    }
                    for($i=1;$i<=(int)$_data['qty'];$i++){
                        $_data['invoice_no'] = $_data['invoice_no'].'_'.$i;
                        $response[] = Purchase::model()->addPurchase($_data);
                    }
                    
                }
                $success = array();
                $failed = array();
                
                foreach($response as $_response){
                    if($_response['status'] == true)
                        $success[] = $_response['data'];
                    else 
                        $failed[] = $_response['data'];
                }
                
                return CJSON::encode( array(
                    'success' => implode(',', $success),
                    'failed' => implode(',', $failed)
                ));
        }
        
        public function actionConfirmUpdate()
        {
            $model=new ConfirmUpdateForm;

            // uncomment the following code to enable ajax-based validation
            /*
            if(isset($_POST['ajax']) && $_POST['ajax']==='confirm-update-form-confirm_update-form')
            {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }
            */
            $response = array();
            $summary = Yii::app()->summary;
            if(isset($_POST['ConfirmUpdateForm']))
            {
                $model->attributes=$_POST['ConfirmUpdateForm'];
                if($model->validate())
                {
                    $file_name = $_POST['ConfirmUpdateForm']['file_name'];
                    $tmp_file_path = realpath($this->upload_path_tmp).DIRECTORY_SEPARATOR.$file_name;                
                
                    $file_info = new SplFileInfo($tmp_file_path);
                    $file_extension = $file_info->getExtension();

                    $work_sheet = Yii::app()->excel->reader($tmp_file_path,$file_extension);
                    $header = Yii::app()->excel->getHeader($work_sheet);
                    unlink($tmp_file_path);
                    if($model->checkFormat($header)){
                        $data = Yii::app()->excel->getRawData($work_sheet);                
                        
                        $merchant_id = Yii::app()->user->getId();
                        $merchant = Merchants::model()->getMerchant($merchant_id);
                        $row = 2;
                        
                        foreach($data as $_data){
                            
                            if($_data['qty'] == 0){
                                    $summary->incrementRecordsRead();
                                }
                                else {
                                    for($i=1;$i<=$_data['qty'];$i++){
                                        $summary->incrementRecordsRead();
                                    }
                                }
                            $error = null;
                            $validate_data = new ValidationData;
                            if(!$validate_data->validateData('confirm_update', $_data, $error)){
                                
                                $duplicate_data = false;
                                
                                if(isset($error['invoice_no'])){
                                    $duplicate_data = true;
                                    unset($error['invoice_no']);  //remove duplicate error
                                }
                                else {
                                    $this->errors[$row] = $error;
                                }                                
                                if($duplicate_data){
                                    if($_data['qty'] == 0)
                                        $summary->incrementDuplicates();
                                    else {
                                        for($i=1;$i<=$_data['qty'];$i++){
                                            $summary->incrementDuplicates();
                                        }
                                    }
                                    
                                    
                                }
                                    
                                else 
                                    $summary->incrementFailed();
                                
                                $row ++;
                                continue;
                            }
                            $_data['merchant_id'] = $merchant_id;
                            $_data['wh_id'] = $merchant->wh_id;
                            $_data['status_id'] = CONFIRMED;
                            $_data['create_date'] = new CDbExpression('Now()');
                            $_data['inv_flag'] = 1;   // means the not allocated to any order
                            $_data['unit_price'] = sprintf("%0.2f",$_data['unit_price']); 

protected/views/merchant/api_purchase.php
<?php
$this->breadcrumbs=array(
	'Order Products'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List OrderProducts','url'=>array('index')),
	array('label'=>'Create OrderProducts','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('order-products-grid', {
		data: $(this).serialize()
	});
	return false;
});
$('.status-change').live('click',function(){
    var r = confirm('Are you sure');
        if (r == true)
          {
            $.getJSON($(this).attr('href'));
            $('#order-products-grid').yiiGridView('update');
          }        
	return false;      
});
");
?>

<h1>Manage Order Products</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>


<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'order-products-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'cart_id',
		'purchase_url',
		array(
                    'class'=>'CButtonColumn',                    
                    'template'=>'{link}{done}',
                    'htmlOptions'=>array('style'=>'width:120px'),
                    'buttons'=>array(
                                  'link' => array(
                                        'label'=>'<span class="btn btn-info">Link</span>',
                                        'url'=>'$data->purchase_url',
                                        'options' => array('title'=>'Link','target'=>'_blank','class'=>'pay-cls')
                                    ), 
                                  'done' => array(
                                        'label'=>'<span class="btn btn-warning">Done</span>',
                                        'url'=>'Yii::app()->createUrl("merchant/changepurchase", array("cart_id"=>$data->cart_id))',
                                        'options'=>array(
                                                'class'=>'status-change','title'=>'Done' 
                                        ),
                                    ),
                                  )
            ), 
	),
)); ?>

protected/views/merchant/api_purchase_.php
<?php
/* @var $this OrderProductsController */
/* @var $model OrderProducts */

$this->breadcrumbs=array(
	'Orders'=>array('index'),
	'Order Overview',
);


Yii::app()->clientScript->registerScript('search', "

$('.search-form form').submit(function(){
	$('#order-products-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
$('.status-change,.progress-cls').live('click',function(){
	var r = confirm('Are you sure');
        if (r == true)
          {
            $.getJSON($(this).attr('href'));
            $('#order-products-grid').yiiGridView('update');
          }
        
	return false;
});
$('.pay-cls').live('click',function(){
    var r = confirm('Are you sure');
        if (r == true)
          {
            $.getJSON($(this).attr('href'),function(data){window.open(data.url,'_blank');});
            $('#order-products-grid').yiiGridView('update');
          }        
	return false;      
});

");
?>

<h1>API Purchase</h1>

<div class="search-form" >
<?php $this->renderPartial('order_overview/_search',array(
	'model'=>$model, 'show_filter' => true
)); ?>
</div><!-- search-form -->
<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'order-products-grid',
	'dataProvider'=>$model->apiPurchase($status_id,$filter_by,$filter_value,$date_range),
        
	'columns'=>array(
                'op_id',
                'merchant.merchant_sku',
                'merchant.api_purchase.price',
                array(
                    'class'=>'CButtonColumn',                    
                    'template'=>'{pay}{pay_one}{done}',
                    'htmlOptions'=>array('style'=>'width:120px'),
                    'buttons'=>array(
                                  'pay' => array(
                                        'label'=>'<span class="btn btn-info">Pay</span>',
                                        'visible'=>'$data->status_id == 1 && isset($data->merchant->api_purchase->purchase_url) && $data->merchant->api_purchase->is_pressed == 0',
                                        'url'=>'($data->merchant->api_purchase->is_pressed == 0)?Yii::app()->createUrl("orders/setpressed", array("op_id"=>$data->op_id)):"#"',
                                        'options' => array('title'=>'Pay','target'=>'_blank','class'=>'pay-cls')
                                    ),  
                                    'pay_one' => array(
                                        'label'=>'<span class="btn">Revert</span>',
                                        'visible'=>'$data->status_id == 1 && isset($data->merchant->api_purchase->purchase_url) && $data->merchant->api_purchase->is_pressed == 1',
                                        'url'=>'Yii::app()->createUrl("orders/change", array("id"=>$data->op_id,"status_id"=>0,"model_name"=>"ApiPurchase"))',
                                        'options' => array('title'=>'Pay','target'=>'_blank','class'=>'progress-cls')
                                    ), 
                                    
                                  'done' => array(
                                        'label'=>'<span class="btn btn-warning">Done</span>',
                                        'visible'=>'$data->status_id == 1 && isset($data->merchant->api_purchase->purchase_url) ',
                                        'url'=>'Yii::app()->createUrl("orders/change", array("id"=>$data->op_id,"status_id"=>2))',
                                        'options'=>array(
                                                'class'=>'status-change','title'=>'Done' 
                                        ),
                                    ),
                                  )
            ),     
	),        
)); ?>

<?php // echo CHtml::ajaxSubmitButton('Yes',array('orderproducts/changeall','act'=>'doActive'), array('success'=>'reloadGrid')); ?>
<?php // echo CHtml::ajaxSubmitButton('No',array('menu/ajaxupdate','act'=>'doInactive'), array('success'=>'reloadGrid')); ?>
<script type="text/javascript">
$('#reportrange').daterangepicker(
    {
      ranges: {
         'Today': [moment(), moment()],
         'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
         'Last 7 Days': [moment().subtract('days', 6), moment()],
         'Last 30 Days': [moment().subtract('days', 29), moment()],
         'This Month': [moment().startOf('month'), moment().endOf('month')],
         'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
      },
      startDate: moment().subtract('days', 29),
      endDate: moment()
    },
    function(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        $('#date_range').val(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }
);
</script>

protected/views/merchant/common_form.php
<?php
/* @var $this ConfirmUpdateFormController */
/* @var $model ConfirmUpdateForm */
/* @var $form CActiveForm */
?>

<div class="form padding">
    <h2><?php echo $title; ?></h2>
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'confirm-update-form-confirm_update-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// See class documentation of CActiveForm for details on this,
	// you need to use the performAjaxValidation()-method described there.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
                    <?php echo CHtml::label('Choose a file to upload','upload'); ?>
                    <?php
                    $this->widget('ext.EAjaxUpload.EAjaxUpload', array(
                        'id' => 'uploadFile',
                        'config' => array(
                            'action' => Yii::app()->createUrl($this->upload_action),
                            'allowedExtensions' => $this->upload_allowed_types, //array("jpg","jpeg","gif","exe","mov" and etc...
                            'sizeLimit' => $this->upload_maxlimit, // maximum file size in bytes
                            //  'minSizeLimit' => 10 * 1024 * 1024, // minimum file size in bytes
                            'onComplete' => "js:function(id, fileName, responseJSON){
                                $('#CommonForm_file_name').val(responseJSON.filename);
                                $('#upload_but').attr('disabled',false).removeClass('disabled');
                        }",
                        )
                    ));
                    ?>
                <?php if($formsetting['type']) { ?>
                    <?php 
                    $type_list = array(1 => 'Upload by PO',2 => 'Upload by Invoice no');
                    echo $form->label($model,'type'); 
                    echo $form->dropDownlist($model,'type',$type_list); ?>
                <?php } ?>
		<?php echo $form->hiddenField($model,'file_name'); ?>
		<?php echo $form->error($model,'file_name'); ?>
                <?php  echo CHtml::link('Download '.  strtolower($title) ,$this->createUrl('merchant/export',array('type'=>'mark_ship_order','format'=>1)),array('id' => 'download_link','style'=>'display: inherit;')); ?>
	</div>


	<div class="row buttons">
                <?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
                        'disabled' => true,
			'type'=>'primary',
			'label'=>'Upload',
                        'htmlOptions' => array(
                            'id' => 'upload_but',
                        )
		)); ?>
	</div>

<?php $this->endWidget(); ?>
<?php $summary->displaySummary(); ?>
<div><?php $summary->printErrLog(); ?></div>
<?php if(!empty($this->errors)) {
   echo '<ul>';
   echo '<li><strong>Row - &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Errors</strong></li>';
   foreach($this->errors as $row => $error){
       $e = array();
       $r = array();
       foreach($error as $key => $message){
           $r[$key] = $message;
       }
        $key = key($r);
        $message = Yii::app()->utility->recursiveImplode($r,',');
        printf('<li>%d -  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  [%s] = [%s]</li>',$row,$key ,$message);
   }
   echo '</ul>';
} ?>           
</div><!-- form -->
<script type="text/javascript">
$('document').ready(function(){
    
    $('#CommonForm_type').on('change',function(e){
        url = '<?php echo $this->createUrl('merchant/export',array('type'=>'mark_ship_order')); ?>';
        url += '&format='+$(this).val();
        $('#download_link').attr('href',url);
        
    });
    
});
</script>

protected/views/merchant/confirm_orders.php
<?php
/* @var $this OrderProductsController */
/* @var $model OrderProducts */

$this->breadcrumbs = array(
    'Merchant' => array('index'),
    'Confirm Orders',
);


Yii::app()->clientScript->registerScript('search', "

$('.search-form form').submit(function(){
	$('#purchase-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Confirmed Orders</h1>
<div class="search-form" >
    <?php
    $this->renderPartial('order_overview/_search', array(
        'model' => $model,
    ));
    ?>
</div><!-- search-form -->
<?php $form=$this->beginWidget('CActiveForm', array(
    'enableAjaxValidation'=>true,
)); ?>
 
<?php
$this->widget('bootstrap.widgets.TbGridView', array(
    'id' => 'purchase-grid',
    'dataProvider' => $model->search($date_range),
    'columns' => array(
        array(
            'id'=>'autoId',
            'class'=>'CCheckBoxColumn',
            'selectableRows' => '50',   
        ),
        'po_id','merchant_id','invoice_no','merchant_sku','description','qty','unit_price','shipping_cost',
        array('header' => 'Purchase Date',
            'value' => 'Yii::app()->dateFormatter->formatDateTime(CDateTimeParser::parse($data->create_date, "yyyy-MM-dd"),"medium",null)'),
    ),
));
?>
<script>
function reloadGrid(data) {
    $.fn.yiiGridView.update('purchase-grid');
    alert('action completed');
}
</script>
<?php echo CHtml::ajaxSubmitButton('Cancel Orders',array('merchant/cancelorders','act'=>'doActive'), array('success'=>'reloadGrid')); ?>
<?php $this->endWidget(); ?>
<script type="text/javascript">
    $('#reportrange').daterangepicker(
            {
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                },
                startDate: moment().subtract('days', 29),
                endDate: moment()
            },
    function(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        $('#date_range').val(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }
    );
</script>

protected/views/merchant/index.php
<?php
/* @var $this MerchantController */

$this->breadcrumbs=array(
	'Merchant',
);
?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>

protected/views/merchant/new_orders.php
<?php
/* @var $this OrderProductsController */
/* @var $model OrderProducts */

$this->breadcrumbs = array(
    'Merchant' => array('index'),
    'New Orders',
);


Yii::app()->clientScript->registerScript('search', "

$('.search-form form').submit(function(){
	$('#order-products-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
$('.status-change').live('click',function(){
	var r = confirm('Are you sure');
        if (r == true)
          {
            $.getJSON($(this).attr('href'));
            $('#order-products-grid').yiiGridView('update');
          }
        
	return false;
});
");
?>

<h1>New Order</h1>
<div class="search-form" >
    <?php
    $this->renderPartial('order_overview/_search', array(
        'model' => $model,
    ));
    ?>
</div><!-- search-form -->
<?php
$this->widget('bootstrap.widgets.TbGridView', array(
    'id' => 'order-products-grid',
    'dataProvider' => $model->overview($status_id, $merchant_id, $date_range,1),
    'columns' => array(
        array('header' => 'Order Date',
            'value' => 'Yii::app()->dateFormatter->formatDateTime($data->create_date,"medium",null)'),
        array('header' => 'Merchant SKU',
            'value' => '$data->merchant->merchant_sku'),
        array('header' => 'Title',
            'value' => 'substr($data->description,0,30)'),
        array('header' => 'Merchant Cost',
            'value' => '$data->merchant->cost'),
        array('header' => 'Qty',
            'value' => '$data->qty'),
        array(
            'class' => 'CButtonColumn',
            'template' => '{no}',
            'htmlOptions' => array('style' => 'width:65px'),
            'buttons' => array(                
                'no' => array(
                    'label' => 'Reject ',
                    'visible' => '$data->status_id == 1',
                    'url' => 'Yii::app()->createUrl("merchant/change", array("id"=>$data->op_id,"status_id"=>4))',
                    'options' => array(
                        'class' => 'status-change',
                    ),
                ),
            )
        ),
    ),
));
?>

<?php // echo CHtml::ajaxSubmitButton('Yes',array('orderproducts/changeall','act'=>'doActive'), array('success'=>'reloadGrid'));  ?>
<?php // echo CHtml::ajaxSubmitButton('No',array('menu/ajaxupdate','act'=>'doInactive'), array('success'=>'reloadGrid'));  ?>
<script type="text/javascript">
    $('#reportrange').daterangepicker(
            {
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                },
                startDate: moment().subtract('days', 29),
                endDate: moment()
            },
    function(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        $('#date_range').val(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }
    );
</script>